# Generated by Django 3.1.6 on 2021-09-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeks', '0002_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='csv',
        ),
        migrations.AddField(
            model_name='csv',
            name='column',
            field=models.ManyToManyField(related_name='csvs', to='planeks.Column'),
        ),
    ]
