# Generated by Django 3.1.6 on 2021-09-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeks', '0004_auto_20210902_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='column_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='column',
            name='type',
            field=models.CharField(choices=[('1', 'Full name'), ('2', 'Job'), ('3', 'Email'), ('4', 'Site'), ('5', 'Phone number'), ('2', 'Company'), ('1', 'Text'), ('2', 'Integer'), ('1', 'Address'), ('2', 'Date')], max_length=50),
        ),
        migrations.AlterField(
            model_name='csv',
            name='column_separator',
            field=models.CharField(choices=[('1', 'Comma(,)'), ('2', 'Semicolon(;)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='csv',
            name='string_characters',
            field=models.CharField(choices=[('1', 'Double-quote(")'), ('2', "Single-quote(')")], max_length=50),
        ),
    ]
