# Generated by Django 3.1.6 on 2021-09-02 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planeks', '0005_auto_20210902_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv',
            name='column',
        ),
        migrations.AddField(
            model_name='column',
            name='csv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planeks.csv'),
        ),
    ]
