# Generated by Django 3.1.6 on 2021-09-02 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planeks', '0007_auto_20210902_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('1', 'Full name'), ('2', 'Job'), ('3', 'Email'), ('4', 'Site'), ('5', 'Phone number'), ('2', 'Company'), ('1', 'Text'), ('2', 'Integer'), ('1', 'Address'), ('2', 'Date')], max_length=50)),
                ('order', models.IntegerField()),
                ('csv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planeks.csv')),
            ],
        ),
    ]
