# Generated by Django 3.1.6 on 2021-09-02 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planeks', '0008_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='csv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='planeks.csv'),
        ),
    ]
