# Generated by Django 3.1.6 on 2021-09-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeks', '0009_auto_20210903_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='type',
            field=models.CharField(choices=[('1', 'Full name'), ('2', 'Job'), ('3', 'Email'), ('4', 'Site'), ('5', 'Phone number'), ('6', 'Company'), ('7', 'Text'), ('8', 'Integer'), ('9', 'Address'), ('10', 'Date')], max_length=50),
        ),
    ]
