# Generated by Django 3.1.6 on 2021-09-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeks', '0010_auto_20210903_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv',
            name='row',
            field=models.IntegerField(null=True),
        ),
    ]
