version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  # redis:
  #   image: "redis:alpine"
  #   ports:
  #     - 6380:6379

  django:
    working_dir: /code/src
    build: .
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8001:8000
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: core.settings


  # celery:
  #   command: celery -A core worker --loglevel=info -E
  #   working_dir: /code/src
  #   build: .
  #   volumes:
  #     - .:/code
  #   depends_on:
  #     - redis
  #     - django
  #   restart: on-failure
  #   environment:
  #     - DJANGO_SETTINGS_MODULE=core.settings

  # beat:
  #   command: celery -A core beat
  #   working_dir: /code/src
  #   build: .
  #   depends_on:
  #     - celery
  #   restart: on-failure
  #   environment:
  #     - DJANGO_SETTINGS_MODULE=core.settings

  # flower:
  #   build: .
  #   working_dir: /code/src
  #   command: celery flower -A core --broker=redis://redis:6380 --loglevel=info --persistent=True
  #   ports:
  #     - 5556:5555
  #   restart: always
  #   depends_on:
  #     - beat
  #   environment:
  #     - DJANGO_SETTINGS_MODULE=core.settings
