FROM python:3-buster
WORKDIR /code

# set env
ENV PYTHONUNBUFFERED=1

# install dependencies
RUN pip install --upgrade pip
COPY requirements.txt /code/
RUN pip install -r requirements.txt

# copy project
COPY . /code/
 
WORKDIR src/

CMD celery -A core worker -B --loglevel=INFO --concurrency=1
